<template>
  <div class="notification-center">
    <button class="notification-trigger" type="button" aria-label="Mở thông báo" :aria-expanded="open" @click="toggle"><span>♢</span><b v-if="unreadCount">{{ unreadCount > 9 ? '9+' : unreadCount }}</b></button>
    <Teleport to="body"><div v-if="open" class="notification-popover"><header><div><span class="eyebrow">LUNU INBOX</span><h2>Thông báo</h2></div><button type="button" class="mark-all" :disabled="!unreadCount" @click="markAll">Đọc tất cả</button></header><div v-if="loading" class="notification-state">Đang đồng bộ...</div><div v-else-if="!items.length" class="notification-state"><span>◌</span><p>Chưa có thông báo mới.</p></div><div v-else class="notification-list"><button v-for="item in items" :key="item.id" class="notification-item" :class="{ unread: !item.is_read }" type="button" @click="read(item)"><span class="notification-icon">{{ iconFor(item.kind) }}</span><span class="notification-copy"><strong>{{ item.title }}</strong><small>{{ item.body }}</small><time>{{ formatTime(item.created_at) }}</time></span><i v-if="!item.is_read"></i></button></div></div></Teleport>
  </div>
</template>

<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { getNotifications, markAllNotificationsRead, markNotificationRead } from '../services/api';

const open = ref(false); const loading = ref(false); const items = ref([]); const unreadCount = ref(0); let timer = null;
const sync = async () => { try { const payload = await getNotifications(); items.value = payload.items || []; unreadCount.value = payload.unread_count || 0; } catch (error) { console.warn('Không thể đồng bộ thông báo:', error.message); } };
const toggle = () => { open.value = !open.value; if (open.value) sync(); };
const read = async (item) => { if (!item.is_read) { item.is_read = true; unreadCount.value = Math.max(0, unreadCount.value - 1); try { await markNotificationRead(item.id); } catch { item.is_read = false; unreadCount.value += 1; } } };
const markAll = async () => { if (!unreadCount.value) return; try { await markAllNotificationsRead(); items.value.forEach((item) => { item.is_read = true; }); unreadCount.value = 0; } catch (error) { console.warn('Không thể đánh dấu thông báo:', error.message); } };
const iconFor = (kind) => kind?.includes('approved') ? '✓' : kind?.includes('rejected') || kind?.includes('failed') ? '!' : '✦';
const formatTime = (value) => { if (!value) return ''; try { return new Date(value).toLocaleString('vi-VN', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }); } catch { return ''; } };
onMounted(() => { sync(); timer = window.setInterval(sync, 30000); }); onBeforeUnmount(() => { if (timer) window.clearInterval(timer); });
</script>

<style scoped>
.notification-center { position: fixed; z-index: 390; top: 20px; right: 24px; }.notification-trigger { position: relative; display: grid; place-items: center; width: 42px; height: 42px; border: 1px solid var(--hairline); border-radius: 13px; background: rgba(13,16,24,.82); color: var(--gold); cursor: pointer; box-shadow: 0 12px 32px rgba(0,0,0,.2); backdrop-filter: blur(12px); }.notification-trigger span { font-size: 22px; transform: rotate(45deg); }.notification-trigger:hover { border-color: rgba(245,185,122,.5); }.notification-trigger b { position: absolute; top: -5px; right: -5px; display: grid; place-items: center; min-width: 18px; height: 18px; padding: 0 4px; border: 2px solid #10131c; border-radius: 99px; background: var(--crimson); color: #fff; font: 8px var(--font-mono); }.notification-popover { position: fixed; top: 72px; right: 24px; width: min(380px, calc(100vw - 32px)); max-height: min(620px, calc(100vh - 90px)); overflow: auto; border: 1px solid var(--hairline); border-radius: 17px; background: #141923; box-shadow: 0 25px 80px rgba(0,0,0,.45); }.notification-popover header { display: flex; align-items: flex-end; justify-content: space-between; padding: 20px; border-bottom: 1px solid var(--hairline-soft); }.eyebrow { margin: 0 0 7px; color: var(--gold); font: 8px var(--font-mono); letter-spacing: 1.7px; }.notification-popover h2 { color: var(--text-main); font: 500 24px var(--font-display); }.mark-all { border: 0; background: transparent; color: var(--gold); cursor: pointer; font-size: 9px; }.mark-all:disabled { opacity: .35; cursor: default; }.notification-state { display: grid; justify-items: center; padding: 48px 20px; color: var(--text-sub); text-align: center; font-size: 11px; }.notification-state span { margin-bottom: 9px; color: var(--gold); font-size: 25px; }.notification-list { padding: 8px; }.notification-item { position: relative; display: flex; align-items: flex-start; gap: 10px; width: 100%; padding: 12px; border: 1px solid transparent; border-radius: 11px; background: transparent; color: var(--text-main); text-align: left; cursor: pointer; }.notification-item:hover, .notification-item.unread { border-color: var(--hairline-soft); background: rgba(255,255,255,.045); }.notification-icon { display: grid; place-items: center; flex: none; width: 27px; height: 27px; border-radius: 9px; background: rgba(245,185,122,.1); color: var(--gold); font-size: 13px; }.notification-copy { display: flex; flex: 1; flex-direction: column; min-width: 0; }.notification-copy strong { font-size: 10px; line-height: 1.4; }.notification-copy small { margin-top: 4px; color: var(--text-sub); font-size: 9px; line-height: 1.45; }.notification-copy time { margin-top: 6px; color: var(--text-faint); font: 8px var(--font-mono); }.notification-item > i { width: 6px; height: 6px; flex: none; border-radius: 50%; background: var(--gold); box-shadow: 0 0 9px var(--gold); }
@media (max-width: 760px) { .notification-center { top: 10px; right: 12px; }.notification-popover { top: 62px; right: 12px; } }
</style>
